package io.github.skydynamic.maiprober

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFA40026)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE9003A)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF9E4039)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF9A91)
val onSecondaryContainerLight = Color(0xFF570A0B)
val tertiaryLight = Color(0xFF5E461D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF86693D)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF97000A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFCF2B27)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF291616)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF291616)
val surfaceVariantLight = Color(0xFFFFDAD9)
val onSurfaceVariantLight = Color(0xFF5E3F3E)
val outlineLight = Color(0xFF936E6D)
val outlineVariantLight = Color(0xFFE8BCBB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF412B2B)
val inverseOnSurfaceLight = Color(0xFFFFEDEC)
val inversePrimaryLight = Color(0xFFFFB3B3)
val surfaceDimLight = Color(0xFFF5D2D1)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EF)
val surfaceContainerLight = Color(0xFFFFE9E8)
val surfaceContainerHighLight = Color(0xFFFFE1E0)
val surfaceContainerHighestLight = Color(0xFFFEDAD9)

val primaryLightMediumContrast = Color(0xFF8B001E)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFE9003A)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF7A2521)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFFBB554D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF563F16)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF86693D)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0008)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2B27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F7)
val onBackgroundLightMediumContrast = Color(0xFF291616)
val surfaceLightMediumContrast = Color(0xFFFFF8F7)
val onSurfaceLightMediumContrast = Color(0xFF291616)
val surfaceVariantLightMediumContrast = Color(0xFFFFDAD9)
val onSurfaceVariantLightMediumContrast = Color(0xFF5A3B3B)
val outlineLightMediumContrast = Color(0xFF795656)
val outlineVariantLightMediumContrast = Color(0xFF977171)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF412B2B)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDEC)
val inversePrimaryLightMediumContrast = Color(0xFFFFB3B3)
val surfaceDimLightMediumContrast = Color(0xFFF5D2D1)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0EF)
val surfaceContainerLightMediumContrast = Color(0xFFFFE9E8)
val surfaceContainerHighLightMediumContrast = Color(0xFFFFE1E0)
val surfaceContainerHighestLightMediumContrast = Color(0xFFFEDAD9)

val primaryLightHighContrast = Color(0xFF4D000C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF8B001E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF4C0205)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF7A2521)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF311F00)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF563F16)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0008)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F7)
val onBackgroundLightHighContrast = Color(0xFF291616)
val surfaceLightHighContrast = Color(0xFFFFF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFFFDAD9)
val onSurfaceVariantLightHighContrast = Color(0xFF371D1D)
val outlineLightHighContrast = Color(0xFF5A3B3B)
val outlineVariantLightHighContrast = Color(0xFF5A3B3B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF412B2B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE6E6)
val surfaceDimLightHighContrast = Color(0xFFF5D2D1)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF0EF)
val surfaceContainerLightHighContrast = Color(0xFFFFE9E8)
val surfaceContainerHighLightHighContrast = Color(0xFFFFE1E0)
val surfaceContainerHighestLightHighContrast = Color(0xFFFEDAD9)

val primaryDark = Color(0xFFFFB3B3)
val onPrimaryDark = Color(0xFF680014)
val primaryContainerDark = Color(0xFFE9003A)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFBFB8)
val onSecondaryDark = Color(0xFF611211)
val secondaryContainerDark = Color(0xFFF8847A)
val onSecondaryContainerDark = Color(0xFF3F0003)
val tertiaryDark = Color(0xFFE5C18D)
val onTertiaryDark = Color(0xFF422C05)
val tertiaryContainerDark = Color(0xFF6A5026)
val onTertiaryContainerDark = Color(0xFFFFF7F1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690004)
val errorContainerDark = Color(0xFFAD0D12)
val onErrorContainerDark = Color(0xFFFFF9F8)
val backgroundDark = Color(0xFF200E0F)
val onBackgroundDark = Color(0xFFFEDAD9)
val surfaceDark = Color(0xFF200E0F)
val onSurfaceDark = Color(0xFFFEDAD9)
val surfaceVariantDark = Color(0xFF5E3F3E)
val onSurfaceVariantDark = Color(0xFFE8BCBB)
val outlineDark = Color(0xFFAE8787)
val outlineVariantDark = Color(0xFF5E3F3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFEDAD9)
val inverseOnSurfaceDark = Color(0xFF412B2B)
val inversePrimaryDark = Color(0xFFBF002E)
val surfaceDimDark = Color(0xFF200E0F)
val surfaceBrightDark = Color(0xFF4A3333)
val surfaceContainerLowestDark = Color(0xFF1A090A)
val surfaceContainerLowDark = Color(0xFF291616)
val surfaceContainerDark = Color(0xFF2E1A1A)
val surfaceContainerHighDark = Color(0xFF3A2424)
val surfaceContainerHighestDark = Color(0xFF452F2F)

val primaryDarkMediumContrast = Color(0xFFFFB9B9)
val onPrimaryDarkMediumContrast = Color(0xFF370006)
val primaryContainerDarkMediumContrast = Color(0xFFFF525F)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFBFB8)
val onSecondaryDarkMediumContrast = Color(0xFF3E0002)
val secondaryContainerDarkMediumContrast = Color(0xFFF8847A)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFE9C591)
val onTertiaryDarkMediumContrast = Color(0xFF211400)
val tertiaryContainerDarkMediumContrast = Color(0xFFAB8C5C)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF200E0F)
val onBackgroundDarkMediumContrast = Color(0xFFFEDAD9)
val surfaceDarkMediumContrast = Color(0xFF200E0F)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9F9)
val surfaceVariantDarkMediumContrast = Color(0xFF5E3F3E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFECC0BF)
val outlineDarkMediumContrast = Color(0xFFC29998)
val outlineVariantDarkMediumContrast = Color(0xFFA07A79)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFFEDAD9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF3A2424)
val inversePrimaryDarkMediumContrast = Color(0xFF940021)
val surfaceDimDarkMediumContrast = Color(0xFF200E0F)
val surfaceBrightDarkMediumContrast = Color(0xFF4A3333)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF1A090A)
val surfaceContainerLowDarkMediumContrast = Color(0xFF291616)
val surfaceContainerDarkMediumContrast = Color(0xFF2E1A1A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3A2424)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF452F2F)

val primaryDarkHighContrast = Color(0xFFFFF9F9)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFB9B9)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9F9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFBAB3)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF7)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFE9C591)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF200E0F)
val onBackgroundDarkHighContrast = Color(0xFFFEDAD9)
val surfaceDarkHighContrast = Color(0xFF200E0F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF5E3F3E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9F9)
val outlineDarkHighContrast = Color(0xFFECC0BF)
val outlineVariantDarkHighContrast = Color(0xFFECC0BF)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFFEDAD9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF5C0011)
val surfaceDimDarkHighContrast = Color(0xFF200E0F)
val surfaceBrightDarkHighContrast = Color(0xFF4A3333)
val surfaceContainerLowestDarkHighContrast = Color(0xFF1A090A)
val surfaceContainerLowDarkHighContrast = Color(0xFF291616)
val surfaceContainerDarkHighContrast = Color(0xFF2E1A1A)
val surfaceContainerHighDarkHighContrast = Color(0xFF3A2424)
val surfaceContainerHighestDarkHighContrast = Color(0xFF452F2F)


val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)
val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)
val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)
val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)